name: CTLeeLab Research
description:  Research brought to you by the ctleelab at the University of California San Diego
url: https://labs.biology.ucsd.edu/ctlee

markdown: kramdown
permalink: /:categories/:title/
future: true
sass:
  sass_dir: css

plugins:
  - jekyll-gzip
  - jekyll-twitter-plugin

gzip:
  replace_files: true

exclude:
  - "*.cpp"
  - "*.csv"
  - "*.gz"
  - "*.h"
  - "*.ipynb"
  - "*.log"
  - "*.py"
  - "*.R"
  - "*.rb"
  - "*.tiff"
  - "*.txt"
  - "*.zip"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "guide/**"
  - "calendar/**"


projects:
  - 
    repo: ctlee/casc
    branch: main
  - 
    repo: ctlee/gamer
    branch: main
  - 
    repo: ctlee/membrane-spectral-analysis
    branch: main
  - 
    repo: RangamaniLabUCSD/Mem3DG
    branch: main
  - 
    repo: RangamaniLabUCSD/ActuAtorForceEstimation
    branch: main
  - 
    repo: RangamaniLabUCSD/smart
    branch: development

  
