name: CTLeeLab Research
description:  Research brought to you by the ctleelab at the University of California San Diego
url: http://labs.biology.ucsd.edu/ctlee

markdown: kramdown
permalink: /:categories/:title/
future: true
sass:
  sass_dir: css

plugins:
  - jekyll-gzip
  - jekyll-twitter-plugin

gzip:
  replace_files: true

exclude:
  - "*.branches"
  - "*.class"
  - "*.cpp"
  - "*.csv"
  - "*.fasta"
  - "*.gz"
  - "*.h"
  - "*.hh"
  - "*.ipynb"
  - "*.jar"
  - "*.java"
  - "*.kml"
  - "*.log"
  - "*.mcc"
  - "*.nb"
  - "*.newick"
  - "*.nex"
  - "*.py"
  - "*.R"
  - "*.rb"
  - "*.Rmd"
  - "*.tiff"
  - "*.tips"
  - "*.trees"
  - "*.tsv"
  - "*.txt"
  - "*.xml"
  - "*.zip"
  - "Gemfile"
  - "Gemfile.lock"

readmes:
  - 
    repo: ctlee/casc
    branch: main
  - 
    repo: ctlee/gamer
    branch: main
  - 
    repo: ctlee/membrane-spectral-analysis
    branch: main
  - 
    repo: RangamaniLabUCSD/Mem3DG
    branch: main
  - 
    repo: RangamaniLabUCSD/ActuAtorForceEstimation
    branch: main
  - 
    repo: RangamaniLabUCSD/smart
    branch: development

projects:
  
